trigger:
  branches:
    include:
      - main

variables:
  imageName: 'onepiece-django-app'
  azureSubscription: 'onepiece-azure-subscription'
  acrLoginServer: 'onepieceacr.azurecr.io'
  kubernetesCluster: 'onepiece-aks'
  kubernetesResourceGroup: 'onepiece_project'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: DockerBuild
    steps:
    - task: Checkout@1

    - task: Docker@2
      inputs:
        containerRegistry: 'onepieceacr-connection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAKS
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: '$(azureSubscription)'
        azureResourceGroup: '$(kubernetesResourceGroup)'
        kubernetesCluster: '$(kubernetesCluster)'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: |
          k8s/deployment.yaml
          k8s/service.yaml
