apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: onepieceacr.azurecr.io/onepiece-django-app:IMAGE_TAG
        ports:
        - containerPort: 8000
        env:
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: youtube-secret
              key: YOUTUBE_API_KEY
        - name: DJANGO_ALLOWED_HOSTS
          value: "127.0.0.1 localhost 4.152.166.35"

